"""
Google OAuth2 credential loader.
Reads token.json (generated by auth_setup.py) and auto-refreshes when expired.
No browser interaction needed after first-time setup.
"""

import os
from pathlib import Path

from dotenv import load_dotenv
from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request

load_dotenv()

SCOPES = [
    "https://www.googleapis.com/auth/calendar",
    "https://www.googleapis.com/auth/spreadsheets",
]

# Resolve paths relative to project root (two levels up from app/services/)
_PROJECT_ROOT = Path(__file__).parent.parent.parent
TOKEN_FILE = _PROJECT_ROOT / os.getenv("GOOGLE_TOKEN_FILE", "token.json")
CLIENT_SECRET_FILE = _PROJECT_ROOT / os.getenv("GOOGLE_CLIENT_SECRET_FILE", "client_secret.json")


def get_credentials() -> Credentials:
    """
    Load and return valid Google OAuth2 credentials.
    Auto-refreshes the token if expired using the stored refresh_token.
    Raises FileNotFoundError if token.json doesn't exist (run auth_setup.py first).
    """
    if not TOKEN_FILE.exists():
        raise FileNotFoundError(
            f"token.json not found at {TOKEN_FILE}. "
            "Please run auth_setup.py first to generate it."
        )

    creds = Credentials.from_authorized_user_file(str(TOKEN_FILE), SCOPES)

    # Refresh token if expired
    if not creds.valid:
        if creds.expired and creds.refresh_token:
            creds.refresh(Request())
            # Persist the refreshed token
            with open(TOKEN_FILE, "w") as f:
                f.write(creds.to_json())
        else:
            raise RuntimeError(
                "Google credentials are invalid and cannot be refreshed. "
                "Please run auth_setup.py again."
            )

    return creds
