[project]
name = "voice-agent-langgraph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "langgraph",
    "langchain-core",
    "google-api-python-client",
    "google-auth",
    "google-auth-oauthlib",
    "python-dotenv",
    "pydantic",
    "pytest",
    "pytest-asyncio",
    "httpx",
    "google_auth_oauthlib",
    "tzdata",
    "langchain-google-genai>=4.2.2",
    "langgraph-checkpoint-sqlite>=3.0.3",
]
